window.esdocSearchIndex = [
  [
    "cs-in-js/src/list/list.js~list",
    "class/src/list/list.js~List.html",
    "<span>List</span> <span class=\"search-result-import-path\">cs-in-js/src/list/list.js</span>",
    "class"
  ],
  [
    "cs-in-js/src/seq.js~seq",
    "class/src/seq.js~Seq.html",
    "<span>Seq</span> <span class=\"search-result-import-path\">cs-in-js/src/seq.js</span>",
    "class"
  ],
  [
    "cs-in-js/src/obj-utils.js~cloneobject",
    "function/index.html#static-function-cloneObject",
    "<span>cloneObject</span> <span class=\"search-result-import-path\">cs-in-js/src/obj-utils.js</span>",
    "function"
  ],
  [
    "cs-in-js/src/array/utils.js~creatematrix",
    "function/index.html#static-function-createMatrix",
    "<span>createMatrix</span> <span class=\"search-result-import-path\">cs-in-js/src/array/utils.js</span>",
    "function"
  ],
  [
    "cs-in-js/src/array/mergesort.js~merge",
    "function/index.html#static-function-merge",
    "<span>merge</span> <span class=\"search-result-import-path\">cs-in-js/src/array/mergeSort.js</span>",
    "function"
  ],
  [
    "cs-in-js/src/array/mergesort.js~mergesort",
    "function/index.html#static-function-mergeSort",
    "<span>mergeSort</span> <span class=\"search-result-import-path\">cs-in-js/src/array/mergeSort.js</span>",
    "function"
  ],
  [
    "cs-in-js/src/array/utils.js~shuffle",
    "function/index.html#static-function-shuffle",
    "<span>shuffle</span> <span class=\"search-result-import-path\">cs-in-js/src/array/utils.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/array/mergesort.js",
    "file/src/array/mergeSort.js.html",
    "src/array/mergeSort.js",
    "file"
  ],
  [
    "src/array/utils.js",
    "file/src/array/utils.js.html",
    "src/array/utils.js",
    "file"
  ],
  [
    "src/list/list.js",
    "file/src/list/list.js.html",
    "src/list/list.js",
    "file"
  ],
  [
    "src/list/list.js~list#constructor",
    "class/src/list/list.js~List.html#instance-constructor-constructor",
    "src/list/list.js~List#constructor",
    "method"
  ],
  [
    "src/list/list.js~list#current",
    "class/src/list/list.js~List.html#instance-method-current",
    "src/list/list.js~List#current",
    "method"
  ],
  [
    "src/list/list.js~list#data",
    "class/src/list/list.js~List.html#instance-member-data",
    "src/list/list.js~List#data",
    "member"
  ],
  [
    "src/list/list.js~list#find",
    "class/src/list/list.js~List.html#instance-method-find",
    "src/list/list.js~List#find",
    "method"
  ],
  [
    "src/list/list.js~list#insert",
    "class/src/list/list.js~List.html#instance-method-insert",
    "src/list/list.js~List#insert",
    "method"
  ],
  [
    "src/list/list.js~list#next",
    "class/src/list/list.js~List.html#instance-method-next",
    "src/list/list.js~List#next",
    "method"
  ],
  [
    "src/list/list.js~list#remove",
    "class/src/list/list.js~List.html#instance-method-remove",
    "src/list/list.js~List#remove",
    "method"
  ],
  [
    "src/list/list.js~list#tostring",
    "class/src/list/list.js~List.html#instance-method-toString",
    "src/list/list.js~List#toString",
    "method"
  ],
  [
    "src/obj-utils.js",
    "file/src/obj-utils.js.html",
    "src/obj-utils.js",
    "file"
  ],
  [
    "src/seq.js",
    "file/src/seq.js.html",
    "src/seq.js",
    "file"
  ],
  [
    "src/seq.js~seq#constructor",
    "class/src/seq.js~Seq.html#instance-constructor-constructor",
    "src/seq.js~Seq#constructor",
    "method"
  ],
  [
    "src/seq.js~seq#current",
    "class/src/seq.js~Seq.html#instance-set-current",
    "src/seq.js~Seq#current",
    "member"
  ],
  [
    "src/seq.js~seq#current",
    "class/src/seq.js~Seq.html#instance-get-current",
    "src/seq.js~Seq#current",
    "member"
  ],
  [
    "src/seq.js~seq#first",
    "class/src/seq.js~Seq.html#instance-method-first",
    "src/seq.js~Seq#first",
    "method"
  ],
  [
    "src/seq.js~seq#last",
    "class/src/seq.js~Seq.html#instance-method-last",
    "src/seq.js~Seq#last",
    "method"
  ],
  [
    "src/seq.js~seq#next",
    "class/src/seq.js~Seq.html#instance-method-next",
    "src/seq.js~Seq#next",
    "method"
  ],
  [
    "src/seq.js~seq#nth",
    "class/src/seq.js~Seq.html#instance-method-nth",
    "src/seq.js~Seq#nth",
    "method"
  ],
  [
    "src/seq.js~seq#values",
    "class/src/seq.js~Seq.html#instance-member-values",
    "src/seq.js~Seq#values",
    "member"
  ]
]